### PR TITLE
Most named character references require a trailing semicolon

### PR DESCRIPTION
**Pull request by afriesen-imvu**
Fixes https://github.com/ndmitchell/tagsoup/issues/27

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks for the bug report and patch, to simplify things, I'll keep all discussion here. Can you please point out where in the spec it identifies that optional semi-colon requirement? (Not saying I doubt you, I'd just like to read the exact language, and also link to it somewhere probably.) And to clarify, you are saying that for certain values of `&foo;` the semi-colon is required rather than optional? If this makes Tagsoup more HTML5 spec compliant then that seems a good idea, especially if you can point to documents/framements that tagsoup gets wrong per the spec but Chrome renders differently (your example from #27 may indeed be such an instance).

Reviewing the actual code seems entirely plausible, although I'll need to take another look in light of the information above.

For info, I'm on holiday Mon-Wed, and am slightly ill at the moment, so may not be able to review patches in detail or give feedback before then.

**Comment by afriesen-imvu** [comment]
I can't find a document that says so directly, but if you look at the charts at http://www.w3.org/TR/html5/syntax.html#named-character-references you'll notice that most entries in the table include the trailing semicolon in their definition.

Further, there are 106 entries in the table that duplicate other entities, but omit the trailing semicolon.

As far as I can tell, popular browsers adhere to this.  I've built a tiny test page here: https://gist.github.com/afriesen-imvu/2bb951518ba08b2ac116

**Comment by ndmitchell** [comment]
Cheers, that sounds pretty convincing - I'll review the code and hope to merge Thursday.

**Comment by ndmitchell** [comment]
I'm afraid my return from holiday was more busy than expected. It's still on my priority pile and I hope to review early next week. Sorry for the delay!

**Comment by andyfriesen** [comment]
It's no trouble.  Happy holidays!

**Comment by ndmitchell** [comment]
Merged, and I added another test to check the implicit ; behaviour as well. I've released it as 0.13.6. Thanks for the change, it is a very subtle bit.

**Pull request merged**
