### PR TITLE
Added a case-insensitive (for element and attribute names) version of…

### PR DESCRIPTION
**Pull request by mikehat**
… Text.HTML.TagSoup.Match.

### CODE REVIEW

**Comment by mikehat** [comment]
Adds an option to the Match module that does case-insensitive matching of element and attribute names.

Pro: makes matches with actual HTML easier.
Con: adds a dependency (case-insensitive)

This module could alternately be a put into its own package and added to hackage. That would keep the new dependency out of the base package, but effectively hide the module from most people who need it (because they probably wouldn't ever see it). If that is your choice, maybe the current tagsoup authors would be the logical owners/maintainers.

Another idea would be to make `CI str` a `StringLike` type. You'd really need to make change some types and refactor to do it right, though. `Attribute s = (s,s)` would have to become `Attribute a b = (a,b)` to allow different comparison behavior between attribute names (possibly case-insensitive) and attribute values (case-sensitive). It's probably more trouble than it's worth.

Feel free to use this (or ignore it) any way you see fit.

**Comment by ndmitchell** [comment]
Looks good, although I'm a little concerned about the `case-insensitive` dependency - it adds a lot of dependencies transitively. With a locally defined `insensitiveEq` wouldn't you be able to get nearly the same benefits with no packages and simpler types as well? It would also remove the unfortunate `Attribute` type.

**Comment by mikehat** [comment]
I agree with the dependency problem. I also feel like adding complexity to the Attribute type is too much rigor for no tangible gain.

I took a peek under the hood of the `case-insensitive` package and it will likely be less efficient than an internal function (it prefers to make two instances of every string). Since the likely reality for tag and attribute names will be a single comparison on the way to GC-land, there's no need to do what `Data.CaseInsensitive.mk` does.

So, I'll clean this up. Which do you prefer:

- Do everything internally in the `MatchCI` module? (least intrusive)
- Add a `insensitiveEq` to the `StringLike` class and implement there?

I'll use `toLower` for `String`, `toCaseFold` for `Text`, and `+ 32` for `ByteString` (only good for ASCII-ish encoding; I can't imagine HTML tags without it).

Any other ideas or suggestions?

**Comment by ndmitchell** [comment]
One thing I wondered about was having a `lowercaseTags :: [Tag a] -> [Tag a]` function, then you could apply that to the tags and the matching would be case-sensitive but guaranteed lowercase. Does that potentially address some of the things you were thinking about?

**Comment by mikehat** [comment]
I made a different pull request on a different branch.

**Pull request closed without merging**
